version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: 'docker.io/dpage/pgadmin4:latest'
    mem_limit: 512m
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 7070:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin/

  app:
    build: .
    command: sh -c "npx prisma migrate deploy && npm run start"
    ports:
      - "8045:8045"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local