version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8045:8045"
    env_file:
      - .env
    depends_on:
      - db
