version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "npx prisma migrate deploy && npm run start"
    ports:
      - "8045:8045"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres-data:
    driver: local